INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (1, 'Pilot', 'December 2, 2013', 'S01E01', 'https://rickandmortyapi.com/api/episode/1');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (2, 'Lawnmower Dog', 'December 9, 2013', 'S01E02', 'https://rickandmortyapi.com/api/episode/2');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (3, 'Anatomy Park', 'December 16, 2013', 'S01E03', 'https://rickandmortyapi.com/api/episode/3');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (4, 'M. Night Shaym-Aliens!', 'January 13, 2014', 'S01E04', 'https://rickandmortyapi.com/api/episode/4');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (5, 'Meeseeks and Destroy', 'January 20, 2014', 'S01E05', 'https://rickandmortyapi.com/api/episode/5');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (6, 'Rick Potion #9', 'January 27, 2014', 'S01E06', 'https://rickandmortyapi.com/api/episode/6');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (7, 'Raising Gazorpazorp', 'March 10, 2014', 'S01E07', 'https://rickandmortyapi.com/api/episode/7');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (8, 'Rixty Minutes', 'March 17, 2014', 'S01E08', 'https://rickandmortyapi.com/api/episode/8');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (9, 'Something Ricked This Way Comes', 'March 24, 2014', 'S01E09', 'https://rickandmortyapi.com/api/episode/9');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (10, 'Close Rick-counters of the Rick Kind', 'April 7, 2014', 'S01E10', 'https://rickandmortyapi.com/api/episode/10');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (11, 'Ricksy Business', 'April 14, 2014', 'S01E11', 'https://rickandmortyapi.com/api/episode/11');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (12, 'A Rickle in Time', 'July 26, 2015', 'S02E01', 'https://rickandmortyapi.com/api/episode/12');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (13, 'Mortynight Run', 'August 2, 2015', 'S02E02', 'https://rickandmortyapi.com/api/episode/13');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (14, 'Auto Erotic Assimilation', 'August 9, 2015', 'S02E03', 'https://rickandmortyapi.com/api/episode/14');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (15, 'Total Rickall', 'August 16, 2015', 'S02E04', 'https://rickandmortyapi.com/api/episode/15');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (16, 'Get Schwifty', 'August 23, 2015', 'S02E05', 'https://rickandmortyapi.com/api/episode/16');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (17, 'The Ricks Must Be Crazy', 'August 30, 2015', 'S02E06', 'https://rickandmortyapi.com/api/episode/17');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (18, 'Big Trouble in Little Sanchez', 'September 13, 2015', 'S02E07', 'https://rickandmortyapi.com/api/episode/18');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (19, 'Interdimensional Cable 2: Tempting Fate', 'September 20, 2015', 'S02E08', 'https://rickandmortyapi.com/api/episode/19');
INSERT INTO public."Episode"(id, name, air_date, episode, url) VALUES (20, 'Look Who''s Purging Now', 'September 27, 2015', 'S02E09', 'https://rickandmortyapi.com/api/episode/20');

INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (1, 'Earth (C-137)', 'Planet', 'Dimension C-137', 'https://rickandmortyapi.com/api/location/1');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (2, 'Abadango', 'Cluster', 'unknown', 'https://rickandmortyapi.com/api/location/2');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (3, 'Citadel of Ricks', 'Space station', 'unknown', 'https://rickandmortyapi.com/api/location/3');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (4, 'Worldender''s lair', 'Planet', 'unknown', 'https://rickandmortyapi.com/api/location/4');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (5, 'Anatomy Park', 'Microverse', 'Dimension C-137', 'https://rickandmortyapi.com/api/location/5');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (6, 'Interdimensional Cable', 'TV', 'unknown', 'https://rickandmortyapi.com/api/location/6');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (7, 'Immortality Field Resort', 'Resort', 'unknown', 'https://rickandmortyapi.com/api/location/7');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (8, 'Post-Apocalyptic Earth', 'Planet', 'Post-Apocalyptic Dimension', 'https://rickandmortyapi.com/api/location/8');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (9, 'Purge Planet', 'Planet', 'Replacement Dimension', 'https://rickandmortyapi.com/api/location/9');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (10, 'Venzenulon 7', 'Planet', 'unknown', 'https://rickandmortyapi.com/api/location/10');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (11, 'Bepis 9', 'Planet', 'unknown', 'https://rickandmortyapi.com/api/location/11');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (12, 'Cronenberg Earth', 'Planet', 'Cronenberg Dimension', 'https://rickandmortyapi.com/api/location/12');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (13, 'Nuptia 4', 'Planet', 'unknown', 'https://rickandmortyapi.com/api/location/13');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (14, 'Giant''s Town', 'Fantasy town', 'Fantasy Dimension', 'https://rickandmortyapi.com/api/location/14');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (15, 'Bird World', 'Planet', 'unknown', 'https://rickandmortyapi.com/api/location/15');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (16, 'St. Gloopy Noops Hospital', 'Space station', 'unknown', 'https://rickandmortyapi.com/api/location/16');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (17, 'Earth (5-126)', 'Planet', 'Dimension 5-126', 'https://rickandmortyapi.com/api/location/17');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (18, 'Mr. Goldenfold''s dream', 'Dream', 'Dimension C-137', 'https://rickandmortyapi.com/api/location/18');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (19, 'Gromflom Prime', 'Planet', 'Replacement Dimension', 'https://rickandmortyapi.com/api/location/19');
INSERT INTO public."Location"(id, name, type, dimension, url) VALUES (20, 'Earth (Replacement Dimension)', 'Planet', 'Replacement Dimension', 'https://rickandmortyapi.com/api/location/20');
